### ISSUE TITLE
怎么处理爬取知乎数据是账户不被封

### ISSUE THREAD

**Issue by panliGit** [wycm/zhihu-crawler#1]
用你的代码试了试爬了不到500条就被封了，怎么处理账户被封呢？

**Comment by wycm** [comment]
请问是哪个版本？

**Comment by panliGit** [comment]
2。0版本，昨天就试了试，大概十来分钟就被封了

**Comment by wycm** [comment]
由于知乎现在有反爬虫机制，如果访问频繁账号会封禁一段时间，不过可以通过发送邮件的方式手动解封的。 我之前跑5个下载线程就被封了。 现在默认下载线程数是3，可以通过 config.properties 配置文件的downloadThreadSize来修改。 最好还是注册一个小号来跑吧。这个反爬虫机制，暂时我也没有比较好的解决方式。
