### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by 554291911** [wycm/zhihu-crawler#10]
爬出来的响应码全是400，403怎么办

**Comment by wycm** [comment]
出现这个问题是因为这个api  https://www.zhihu.com/api/v4/members/%s/followees?include=data[*].educations,employments,answer_count,business,locations,articles_count,follower_count,gender,following_count,question_count,voteup_count,thanked_count,is_followed,is_following,badge[?(type=best_answerer)].topics&offset=%d&limit=20
不能获取到关注人数了，导致线程池任务不能持续下去。我刚刚把抓取方式切换成以前的detail和list分开抓取了，这种方式抓取速率会降低，你重新更新下代码就可以了。
另外400,403状态码只是代理检测的状态码
