### ISSUE TITLE
关于关闭线程池问题

### ISSUE THREAD

**Issue by hahachiu** [wycm/zhihu-crawler#11]
想请问关于线程池的关闭是在config文件配置downloadPageCount属性进行判断结束条件为依据的嘛？如果是这样好像线程池一直都没达到关闭的情形。希望可以解答。最后十分感谢大神的代码。

**Comment by wycm** [comment]
是以downdloadPageCount属性作为线程池结束条件的。最开始版本的时候是考虑到正常关闭线程池，更新几次后，都没有考虑到关闭线程池了。如果需要的话，我明天修复下这个问题。

**Comment by hahachiu** [comment]
用原来注释的代码暂时做到关闭线程池的操作，不急。保持关注，持续学习 ，谢谢。

**Comment by wycm** [comment]
问题修复了，见最新代码
