### ISSUE TITLE
proxies 打开乱码

### ISSUE THREAD

**Issue by unikcc** [wycm/zhihu-crawler#17]
proxies乱码是怎么回事呢，试了各种编码格式了

**Comment by wycm** [comment]
这个文件是序列化的对象，不是文本文件。

**Comment by nkhouse** [comment]
额，我问的问题多弱智=_=....还有个问题，那个proxy的延时队列DelayQueue的时间在哪设置呢，就是add以后多长时间后可以take，我找了代码里面好像没有设置，，搜了一下默认延迟时间也没找到是多少
