### ISSUE TITLE
连接数据库异常

### ISSUE THREAD

**Issue by yuquanle** [wycm/zhihu-crawler#18]
java.sql.SQLException: Illegal connection port value 'mysql:'

我修改配置为：
db.enable = true
# 数据库配置
db.host = jdbc:mysql://localhost:3306/zhihu
db.username = root
db.password = 123456
# 数据库名
db.name = zhihu

**Comment by wycm** [comment]
修改成
db.host = localhost

**Comment by yuquanle** [comment]
感谢 已star
