### ISSUE TITLE
按照你的代码跑,报了一个错误

### ISSUE THREAD

**Issue by TMdicYMZ** [wycm/zhihu-crawler#2]
Host name 'XXXXXXXXX' does not match the certificate subject provided by the peer
可参考
http://stackoverflow.com/questions/34655031/javax-net-ssl-sslpeerunverifiedexception-host-name-does-not-match-the-certifica
修改一下
然后就行了,
感谢up的代码.

**Comment by wycm** [comment]
谢谢
