### ISSUE TITLE
你好，我想问下，Main类下“        ZhiHuHttpClient.getInstance().startCrawl();” 这段是怎么循环的？

### ISSUE THREAD

**Issue by youliang999** [wycm/zhihu-crawler#23]
@Override
    public void startCrawl() {
        authorization = initAuthorization();

        String startToken = Config.startUserToken;
        String startUrl = String.format(Constants.USER_FOLLOWEES_URL, startToken, 0);
        HttpGet request = new HttpGet(startUrl);
        request.setHeader("authorization", "oauth " + ZhiHuHttpClient.getAuthorization());
        detailListPageThreadPool.execute(new DetailListPageTask(request, Config.isProxy));
        manageHttpClient();
    }

这段是怎么保证他一直在抓取数据呢，怎么维持这个抓取逻辑的循环呢？

**Comment by wycm** [comment]
DetailListPageTask这个任务执行过程中会不断构造新的任务添加到detailListPageThreadPool线程池

**Comment by youliang999** [comment]
谢谢！
