### ISSUE TITLE
你好，我第一次接触爬虫，不是很了解！

### ISSUE THREAD

**Issue by linfeipeng** [wycm/zhihu-crawler#24]
我想问一下，为什么我运行起来，显示可用代理为0呢，还有就是一直报400,500，是需要配置什么吗？希望楼主能够回答，万分感谢！

**Comment by wycm** [comment]
现在重新更新下代码，可以跑起来了

**Comment by linfeipeng** [comment]
来反馈一下，能跑起来了，非常棒，对我学习很有帮助，谢谢楼主解答。

**Comment by linfeipeng** [comment]
楼主你好！关于获取“我的关注”中，有一段代码不是很理解：
String type = "['" + userToken + "']";//转义
String commonJsonPath = "$.entities.users." + type;
try {
            JsonPath.parse(dataStateJson).read(commonJsonPath);
} catch (PathNotFoundException e){
            commonJsonPath = "$.entities.users.null";
}
我想问一下，这段代码中，我没有在html文件中，找到$.entities.users.标签，这个是如何获取的。
JsonPath的用法是起什么作用？希望能够得到楼主解答，万分感谢！

**Comment by wycm** [comment]
@linfeipeng  这个是处理json数据的，这个数据没有在html中。jsonpath在这里的作用是从json格式串中解析出需要的数据。和xpath类似的一个东西，不过xpath解析的数据是html格式串，jsonpath是解析的json格式串。
