### ISSUE TITLE
你好，是不是可以加个饱和策略

### ISSUE THREAD

**Issue by shanyao19940801** [wycm/zhihu-crawler#25]
你好，看你代码[DetailListPageTask](https://github.com/wycm/zhihu-crawler/blob/2.0/src/main/java/com/crawl/zhihu/task/DetailListPageTask.java)中有一段：

`if (zhiHuHttpClient.getDetailListPageThreadPool().getQueue().size() > 1000){
                        continue;
                    }`
我觉得当线程并发量上去后，这段代码还是很消耗资源的。
可以给线程池添加一个Descar饱和策略，最大线程以及阻塞队列都满了后继续添加任务直接抛弃掉。和你的这段代码效果一样，但是有线程池来抛弃效率肯定会更好。

**Comment by wycm** [comment]
你说的是DiscardPolicy丢弃策略吧？
我大致看了源码，好像这里的效率不会比DiscardPolicy低，我这种方式只做了个任务队列长度的判断。如果当任务队列长度达到一定后，而execute方法进去会有3个过程，第一步corePoolSize和当前runningPoolSize大小比较。第二步然后workQueue.offer这个方法，这个方法进去里面都包括了任务队列长度的判断了。如果第二步添加失败，再执行丢弃策略。
另外其实早期写的时候对线程池的拒绝策略不太了解，所以有了以上写法。你说的这种方式更直观可读一些吧
