### ISSUE TITLE
ActiveMQ 需要配置吗

### ISSUE THREAD

**Issue by LungLee** [wycm/zhihu-crawler#3]
你好：
JMS Exception-Could not connect to broker url
我启动之后就报这个错误，是不是ActiveMQ 需要配置下？
http://localhost:8161/admin/queues.jsp
这个url我也登不上

**Comment by wycm** [comment]
ActiveMQ 是2.1版本的东西，这个版本还没有做好。
你切换到2.0版本就可以了。操作如下
进到mycrawler目录下
git branch -a
git checkout 2.0

**Comment by LungLee** [comment]
ok 谢谢你

**Comment by little-Fly** [comment]
写的不错，就是我现在的水平读起来还很费劲，还有我每次运行为啥只能爬到20多个然后就停止了？
