### ISSUE TITLE
嗨，你好

### ISSUE THREAD

**Issue by little-Fly** [wycm/zhihu-crawler#4]
刚才好像回错地方了，还不太会用这个！为啥我每次只爬到20多个就停掉了呢？

**Comment by wycm** [comment]
把config.properties文件中的
downloadPageCount = 20
调大一点就OK了

**Comment by little-Fly** [comment]
哦哦，谢谢，我在好好研究下！

**Comment by little-Fly** [comment]
没怎么用过多线程，看的我好费脑筋=_=

**Comment by wycm** [comment]
就只用了线程池
