### ISSUE TITLE
com.crawl.zhihu.task.ParseTask.handleUrl方法  防止死锁

### ISSUE THREAD

**Issue by shixiangweii** [wycm/zhihu-crawler#5]
首先，感谢大神的code和doc，已正常从知乎抓取了数据，但有些地方，小弟不是很明白，想请教一下。
` private void handleUrl(String url){
        if(!Config.dbEnable){
            zhiHuHttpClient.getDownloadThreadExecutor().execute(new DownloadTask(url));
            return ;
        }
        String md5Url = Md5Util.Convert2Md5(url);
        boolean isRepeat = ZhiHuDAO.insertHref(md5Url);
    #     _**if(!isRepeat ||
                (!zhiHuHttpClient.getDownloadThreadExecutor().isShutdown() &&
                        zhiHuHttpClient.getDownloadThreadExecutor().getQueue().size() < 30)){
            /**
             * 防止互相等待，导致死锁
             */
            zhiHuHttpClient.getDownloadThreadExecutor().execute(new DownloadTask(url));**
        }_
    }`

这个方法中的防止死锁，为什么这样可以防止死锁？或者说为什么会有产生死锁的可能？
不是很懂（java concurrent包中的很多类都不是很懂），

**Comment by wycm** [comment]
这里准确的说不叫死锁，应该叫活锁吧。
防止出现下面这种情况，当抓取的用户一定多后，可能会出现某个用户的关注用户里面已经全部抓取。这个时候就新的url就不会被添加到downloadThreadPool中。这个时候可能会出现downloadThreadPool和parseThreadPool互相等待对方提供任务的情况。就锁住了。

**Comment by shixiangweii** [comment]
多谢回答，那是不是这样判断处理了
`!isRepeat ||(!zhiHuHttpClient.getDownloadThreadExecutor().isShutdown() &&zhiHuHttpClient.getDownloadThreadExecutor().getQueue().size() < 30)`
避免了可能存在的互相等待，但是不是就会有数据重复的情况？

**Comment by wycm** [comment]
数据库里面的数据不会重复，只是会重复抓取。

**Comment by shixiangweii** [comment]
OK
