### ISSUE TITLE
关于代理的问题

### ISSUE THREAD

**Issue by shixiangweii** [wycm/zhihu-crawler#8]
大神，我实际跑了你的代码，现在项目文档中说的代理我的理解是不是指，用www.xicidaili.com提供的代理服务器来访问知乎，避免知乎的防抓取？
PS.试过把main中的ProxyHttpClient.getInstance().startCrawl();注释掉，结果就是大量的429，Too Many Requests (太多请求)

**Comment by shixiangweii** [comment]
还有就是，我工作的地方网络访问有限制（之前是用自己的网跑的），访问外网是通过配置IE中的代理服务器的，这种情况下，
我还在哪里添加对httpClent的设置代理服务器的代码？

**Comment by wycm** [comment]
不是通过www.xicidaili.com来代理的。而是去抓取的这个网站上的http代理来当作代理服务器。429就是因为同一个客户端并发访问量过高

**Comment by shixiangweii** [comment]
原来是这样的啊

**Comment by wycm** [comment]
https://github.com/wycm/zhihu-crawler/blob/2.0/src/main/java/com/crawl/core/util/HttpClientUtil.java
58行，设置代理就可以了。

**Comment by shixiangweii** [comment]
OK,多谢大神

**Comment by shixiangweii** [comment]
感觉线程池，httpclient用得挺溜的，大神有什么经验可以教一下的，有博客什么的吗？

**Comment by wycm** [comment]
过奖了，主要还是看官方教程和相关博客。
暂时没有博客。
