### ISSUE TITLE
IDEA导入失败，依赖不识别

### ISSUE THREAD

**Issue by doudouhasdoudou** [wycm/zhihu-crawler#9]
想问一下，JDK用的是什么版本，以及IDEA版本号，我的导入总是失败

**Comment by lcy362** [comment]
我用的jdk7 和idea最新版没问题。
跟idea版本应该没关系吧。
具体报什么错?

**Comment by doudouhasdoudou** [comment]
问题已经解决了，跟jdk没关系，改了下pom.xml文件重的log4j把1.2.15改为1.2.16就好了，打扰你了，，

**Comment by wycm** [comment]
环境windows7+idea+Bundled (Maven 3)，导入项目也遇到这个问题了，pom.xml文件中的log4j把1.2.15改为1.2.16。
